version: '2'

services:
 web:
     build:
         context: .
         dockerfile: docker/Dockerfile_app
     image: wp-web
     hostname: wp-web
     container_name: wp-web
     ports:
         - "8081:80"
     networks:
         deep:
             ipv4_address: 124.0.0.76

 redis:
     build:
         context: .
         dockerfile: docker/Dockerfile_redis
     image: wp-redis
     hostname: wp-redis
     container_name: wp-redis
     ports:
         - "6379:6379"
     networks:
         deep:
             ipv4_address: 124.0.0.77

 mysql-db:
     build:
         context: .
         dockerfile: docker/Dockerfile_mysql
     image: wp-mysql
     hostname: wp-mysql
     container_name: wp-mysql
     ports:
         - "3306:3306"
     networks:
         deep:
             ipv4_address: 124.0.0.78

networks:
  deep:
    driver: bridge
    ipam:
     config:
       - subnet: 124.0.0.0/24
