FROM centos:centos7
EXPOSE 3306
### Add package Maria-db
ADD /configs/mariadb/etc/yum.repos.d/MariaDB.repo /etc/yum.repos.d/
RUN yum update -y && yum install -y epel-release
RUN yum install -y mariadb-server

# Install s6overlay
RUN curl -LSs -o /tmp/s6-overlay-amd64.tar.gz \
    https://github.com/just-containers/s6-overlay/releases/download/v1.21.0.0/s6-overlay-amd64.tar.gz && \
    tar xzf /tmp/s6-overlay-amd64.tar.gz -C / --exclude="./bin" --exclude="./sbin" && \
    tar xzf /tmp/s6-overlay-amd64.tar.gz -C /usr ./bin
# Hardcode
RUN mysqld_safe & until mysqladmin ping; do sleep 1; done && \
    mysql -uroot -e "CREATE DATABASE wpdb;" && \
    mysql -uroot -e "CREATE USER 'wpuser'@'localhost' IDENTIFIED BY 'wppasswd';" && \
    mysql -uroot -e "GRANT ALL PRIVILEGES ON wpdb.* TO 'wpuser' IDENTIFIED BY 'wppasswd' WITH GRANT OPTION;"
CMD ["usr/bin/mysqld_safe"]
ENTRYPOINT ["/init"]
