FROM centos:centos7

# Descriptions
MAINTAINER https://www.saritasa.com
LABEL Vendor="Saritasa" \
      Project="WordpressFW"

# System update, add epel-release and instal apache web-server
RUN yum -y update && yum -y install epel-release && yum -y install httpd unzip mysql

# Install s6overlay
RUN curl -LSs -o /tmp/s6-overlay-amd64.tar.gz \
    https://github.com/just-containers/s6-overlay/releases/download/v1.21.0.0/s6-overlay-amd64.tar.gz && \
    tar xzf /tmp/s6-overlay-amd64.tar.gz -C / --exclude="./bin" --exclude="./sbin" && \
    tar xzf /tmp/s6-overlay-amd64.tar.gz -C /usr ./bin

# Add Remi repo
RUN rpm -Uvh http://rpms.remirepo.net/enterprise/remi-release-7.rpm && yum -y install yum-utils %% yum -y update

# Install PHP 7.2
RUN yum-config-manager --enable remi-php72 && yum -y install php php-mysql php-xml php-soap php-xmlrpc php-mbstring php-json php-gd php-mcrypt php72-php-pecl-redis php-redis

# Download and put WordPress into DocumentRoot
RUN curl -LSs -o  /tmp/wordpress.zip https://wordpress.org/latest.zip && \
    unzip /tmp/wordpress.zip -d /var/www/html/

EXPOSE 80
ENTRYPOINT ["/init"]
#ENTRYPOINT ["/usr/sbin/httpd","-D","FOREGROUND"]

# Add configs
ADD configs/app/ /
